apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    spec:
      containers:
        - name: modelserver
          args:
            - "Qwen/Qwen3-32B"
            - "--tensor-parallel-size=2"
            - "--kv-transfer-config"
            - '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_both"}'
            - "--max-num-seqs=1024"
          resources:
            limits:
              memory: 500Gi
            requests:
              memory: 500Gi
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            - name: LMCACHE_MAX_LOCAL_CPU_SIZE
              value: "100.0"
            - name: PYTHONHASHSEED
              value: "123"
            - name: PROMETHEUS_MULTIPROC_DIR
              value: "/tmp/lmcache_prometheus"
          volumeMounts:
            - name: lmcache-prometheus-metrics
              mountPath: /tmp/lmcache_prometheus
      volumes:
        - name: lmcache-prometheus-metrics
          emptyDir: {}
