apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/default

namePrefix: amd-vllm-

components:
  - ../../../../../recipes/modelserver/components/images/amd-vllm

labels:
  - pairs:
      llm-d.ai/model: Qwen3-32B
      llm-d.ai/guide: tiered-prefix-cache
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: amd
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-vllm.yaml
